### ISSUE TITLE
Fix `accountapp` chart issue: `invalid value; expected string`

### ISSUE THREAD

**Issue by linoleparquet** [jenkins-infra/helm-charts#725] opened 2023-09-20 18:29 UTC
Hey!

While separating test with default values and custom values in chart `accountapp` as discussed [here](https://github.com/jenkins-infra/helm-charts/pull/715#discussion_r1331639758), I encountered an error:

`helm template accountapp` output: 
Error: template: accountapp/templates/secret.yaml:10:43: executing "accountapp/templates/secret.yaml" at <b64enc>: invalid value; expected string

I'm creating a PR that will adress both issues.

**Comment by dduportal** [comment] 2023-09-21 06:56
Closed by #726

**Closed by dduportal** 2023-09-21 06:56 UTC

**Comment by lemeurherve** [comment] 2023-09-21 08:06
Duplicate of https://github.com/jenkins-infra/helm-charts/issues/654
